version: "3.7"

services:
  rmq:
    image: rabbitmq:3.9.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    container_name: test_rmq